"""Add party and date fields to contracts

Revision ID: 01e3474bdb28
Revises: fae457f97069
Create Date: 2026-09-04 14:52:24.836882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e3474bdb28'
down_revision = 'fae457f97069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Party_A', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('Party_B', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('Effective_Date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('Expiry_Date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('Expiry_Date')
        batch_op.drop_column('Effective_Date')
        batch_op.drop_column('Party_B')
        batch_op.drop_column('Party_A')

    
    # ### end Alembic commands ###
