"""Add version and clause constraints

Revision ID: 239b4d2087c6
Revises: b2f96f84a803
Create Date: 2026-09-10 00:29:45.593106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239b4d2087c6'
down_revision = 'b2f96f84a803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('clauses', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_version_clause_number', ['Version_ID', 'Clause_Number'])

    with op.batch_alter_table('contract_versions', schema=None) as batch_op:
        batch_op.create_index('uq_current_contract_version', ['Contract_ID'], unique=True, postgresql_where=sa.text('"Is_Current" = true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_versions', schema=None) as batch_op:
        batch_op.drop_index('uq_current_contract_version', postgresql_where=sa.text('"Is_Current" = true'))

    with op.batch_alter_table('clauses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_version_clause_number', type_='unique')

   
    # ### end Alembic commands ###
