"""initial database schema

Revision ID: 23fa02300e4f
Revises: 
Create Date: 2026-08-30 16:37:44.929120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fa02300e4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_statuses',
    sa.Column('Status_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Status_Name', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('Status_ID'),
    sa.UniqueConstraint('Status_Name')
    )
    op.create_table('contract_types',
    sa.Column('Contract_Type_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Contract_Type_Name', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('Is_Active', sa.Boolean(), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('Contract_Type_ID'),
    sa.UniqueConstraint('Contract_Type_Name')
    )
    op.create_table('roles',
    sa.Column('Role_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Role_Name', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('Role_ID'),
    sa.UniqueConstraint('Role_Name')
    )
    op.create_table('users',
    sa.Column('User_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('Phone_No', sa.String(length=20), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('Role_ID', sa.Integer(), nullable=False),
    sa.Column('Created_By', sa.Integer(), nullable=True),
    sa.Column('Updated_By', sa.Integer(), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Created_By'], ['users.User_ID'], ),
    sa.ForeignKeyConstraint(['Role_ID'], ['roles.Role_ID'], ),
    sa.ForeignKeyConstraint(['Updated_By'], ['users.User_ID'], ),
    sa.PrimaryKeyConstraint('User_ID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('contracts',
    sa.Column('Contract_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Contract_Name', sa.String(length=200), nullable=False),
    sa.Column('Contract_Type_ID', sa.Integer(), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Status_ID', sa.Integer(), nullable=False),
    sa.Column('Created_By', sa.Integer(), nullable=False),
    sa.Column('Updated_By', sa.Integer(), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Contract_Type_ID'], ['contract_types.Contract_Type_ID'], ),
    sa.ForeignKeyConstraint(['Created_By'], ['users.User_ID'], ),
    sa.ForeignKeyConstraint(['Status_ID'], ['contract_statuses.Status_ID'], ),
    sa.ForeignKeyConstraint(['Updated_By'], ['users.User_ID'], ),
    sa.PrimaryKeyConstraint('Contract_ID')
    )
    op.create_table('documents',
    sa.Column('Document_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Contract_ID', sa.Integer(), nullable=False),
    sa.Column('Document_Name', sa.String(length=200), nullable=False),
    sa.Column('File_Path', sa.String(length=500), nullable=False),
    sa.Column('Document_Type', sa.String(length=50), nullable=False),
    sa.Column('Status', sa.String(length=30), nullable=False),
    sa.Column('Created_By', sa.Integer(), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_By', sa.Integer(), nullable=True),
    sa.Column('Updated_At', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Contract_ID'], ['contracts.Contract_ID'], ),
    sa.ForeignKeyConstraint(['Created_By'], ['users.User_ID'], ),
    sa.ForeignKeyConstraint(['Updated_By'], ['users.User_ID'], ),
    sa.PrimaryKeyConstraint('Document_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('contracts')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('contract_types')
    op.drop_table('contract_statuses')
    # ### end Alembic commands ###
