"""create modifications table

Revision ID: 3a2658df773c
Revises: 239b4d2087c6
Create Date: 2026-09-11 14:30:46.074142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2658df773c'
down_revision = '239b4d2087c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Modification_Type', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('Status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('Reviewed_By', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Reviewed_At', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('Review_Comment', sa.Text(), nullable=True))
        batch_op.alter_column('Clause_ID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['Reviewed_By'], ['User_ID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('Clause_ID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('Review_Comment')
        batch_op.drop_column('Reviewed_At')
        batch_op.drop_column('Reviewed_By')
        batch_op.drop_column('Status')
        batch_op.drop_column('Modification_Type')

    # ### end Alembic commands ###
