"""create contract versions table

Revision ID: 9a3a19dd2848
Revises: 23fa02300e4f
Create Date: 2026-08-31 22:59:06.778537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3a19dd2848'
down_revision = '23fa02300e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_versions',
    sa.Column('Version_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Contract_ID', sa.Integer(), nullable=False),
    sa.Column('Document_ID', sa.Integer(), nullable=False),
    sa.Column('Version_Number', sa.Integer(), nullable=False),
    sa.Column('File_Path', sa.String(length=500), nullable=False),
    sa.Column('Change_Summary', sa.Text(), nullable=True),
    sa.Column('Created_By', sa.Integer(), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Is_Current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Contract_ID'], ['contracts.Contract_ID'], ),
    sa.ForeignKeyConstraint(['Created_By'], ['users.User_ID'], ),
    sa.ForeignKeyConstraint(['Document_ID'], ['documents.Document_ID'], ),
    sa.PrimaryKeyConstraint('Version_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_versions')
    # ### end Alembic commands ###
