"""Add assigned user to contracts

Revision ID: b2f96f84a803
Revises: 01e3474bdb28
Create Date: 2026-09-09 22:25:08.296940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f96f84a803'
down_revision = '01e3474bdb28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_users',
    sa.Column('Contract_User_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Contract_ID', sa.Integer(), nullable=False),
    sa.Column('User_ID', sa.Integer(), nullable=False),
    sa.Column('Assigned_By', sa.Integer(), nullable=False),
    sa.Column('Assigned_At', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Assigned_By'], ['users.User_ID'], ),
    sa.ForeignKeyConstraint(['Contract_ID'], ['contracts.Contract_ID'], ),
    sa.ForeignKeyConstraint(['User_ID'], ['users.User_ID'], ),
    sa.PrimaryKeyConstraint('Contract_User_ID'),
    sa.UniqueConstraint('Contract_ID', 'User_ID', name='uq_contract_user')
    )
    
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('Created_By',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('Created_By',
               existing_type=sa.INTEGER(),
               nullable=True)

    
    op.drop_table('contract_users')
    # ### end Alembic commands ###
