"""create clauses table

Revision ID: fae457f97069
Revises: 9a3a19dd2848
Create Date: 2026-08-31 23:33:40.494920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae457f97069'
down_revision = '9a3a19dd2848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clauses',
    sa.Column('Clause_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Contract_ID', sa.Integer(), nullable=False),
    sa.Column('Version_ID', sa.Integer(), nullable=False),
    sa.Column('Clause_Number', sa.Integer(), nullable=False),
    sa.Column('Clause_Title', sa.String(length=200), nullable=False),
    sa.Column('Clause_Text', sa.Text(), nullable=False),
    sa.Column('Created_By', sa.Integer(), nullable=False),
    sa.Column('Updated_By', sa.Integer(), nullable=True),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_At', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Contract_ID'], ['contracts.Contract_ID'], ),
    sa.ForeignKeyConstraint(['Created_By'], ['users.User_ID'], ),
    sa.ForeignKeyConstraint(['Updated_By'], ['users.User_ID'], ),
    sa.ForeignKeyConstraint(['Version_ID'], ['contract_versions.Version_ID'], ),
    sa.PrimaryKeyConstraint('Clause_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clauses')
    # ### end Alembic commands ###
